# Generated by Django 4.2.11 on 2024-04-30 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitant',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.apartment', verbose_name='Apartamento'),
        ),
        migrations.AlterField(
            model_name='inhabitantpayments',
            name='inhabitant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.inhabitant', verbose_name='Residente'),
        ),
        migrations.AlterField(
            model_name='inhabitantvehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.inhabitant', verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='inhabitantvehicle',
            name='parking_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.parkingplace', verbose_name='Parqueadero'),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='barcode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de barras del carnet'),
        ),
    ]
