# Generated by Django 4.2.11 on 2024-05-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0002_alter_inhabitant_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplace',
            name='user_type',
            field=models.CharField(choices=[('I', 'Residentes'), ('V', 'Visitantes')], default='I', max_length=1, verbose_name='Para ser usado por'),
        ),
    ]
