# Generated by Django 4.2.11 on 2024-05-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0003_alter_parkingplace_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplace',
            name='user_type',
            field=models.CharField(choices=[('I', 'Residentes'), ('V', 'Visitantes'), ('M', 'MultiUso')], default='I', max_length=1, verbose_name='Para ser usado por'),
        ),
    ]
