# Generated by Django 4.2.11 on 2024-04-30 01:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0002_alter_inhabitant_apartment_and_more'),
        ('security_guard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitantparkinguse',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='inhabitantparkinguse',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.inhabitantvehicle', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='visitorparkinguse',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='visitorparkinguse',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_guard.visitorvehicle', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='visitorspayments',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_guard.visitor', verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='visitorvehicle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security_guard.visitor', verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='visitorvehicle',
            name='parking_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.parkingplace', verbose_name='Parqueadero'),
        ),
    ]
