# Generated by Django 4.2.11 on 2024-05-01 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0003_alter_parkingplace_user_type'),
        ('security_guard', '0002_alter_inhabitantparkinguse_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visitorvehicle',
            options={},
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='identification',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='identification_type',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='axis',
        ),
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='parking_place',
        ),
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='type',
        ),
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='weight',
        ),
        migrations.AddField(
            model_name='visitor',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.apartment', verbose_name='Apartamento'),
            preserve_default=False,
        ),
    ]
