# Generated by Django 4.2.11 on 2024-05-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_guard', '0003_alter_visitor_options_alter_visitorvehicle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorvehicle',
            name='type',
            field=models.CharField(choices=[('C', 'Carro'), ('M', 'Moto'), ('B', 'Bicicleta')], default='C', max_length=1, verbose_name='Tipo de vehiculo'),
            preserve_default=False,
        ),
    ]
