# Generated by Django 4.2.11 on 2024-05-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_guard', '0004_visitorvehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorspayments',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del pago'),
        ),
    ]
