# Generated by Django 4.2.11 on 2024-05-04 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_guard', '0005_alter_visitorspayments_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitantparkinguse',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de inicio del turno'),
        ),
        migrations.AlterField(
            model_name='visitorparkinguse',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='visitorspayments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha del pago'),
        ),
    ]
