# Generated by Django 3.2.4 on 2021-08-20 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_co_ownership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.coownership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('identification_type', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería')], default='CC', max_length=2, verbose_name='Tipo de identificación')),
                ('identification', models.BigIntegerField(unique=True, verbose_name='Documento de identificación')),
                ('cellphone', models.BigIntegerField(verbose_name='Número de celular')),
                ('co_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.coownership')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorsPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del pago')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor del pago')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_guard.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio del turno')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Fecha de fin del turno')),
                ('starting_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero inicial')),
                ('final_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinero final')),
                ('security_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_guard.securityguard')),
            ],
        ),
        migrations.CreateModel(
            name='InhabitantParkingUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('departure_date', models.DateTimeField(null=True, verbose_name='Fecha y hora de salida')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.inhabitantvehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
