# Generated by Django 3.2.4 on 2021-08-20 17:00

import admin_co_ownership.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0001_initial'),
        ('security_guard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Marca del vehiculo')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo del vehiculo')),
                ('type', models.CharField(choices=[('C', 'Carro'), ('M', 'Moto'), ('B', 'Bicicleta')], max_length=1, verbose_name='Tipo de vehiculo')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('axis', models.IntegerField(verbose_name='Número de ejes')),
                ('plate', models.CharField(max_length=8, verbose_name='Número de placa')),
                ('picture', models.ImageField(upload_to=admin_co_ownership.models.photo_directory_path, verbose_name='Foto a color')),
                ('dummy', models.CharField(default='dummy', max_length=8, verbose_name='dummy')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security_guard.visitor')),
                ('parking_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.parkingplace')),
            ],
            options={
                'ordering': ['brand', 'model', 'type'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorParkingUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('departure_date', models.DateTimeField(null=True, verbose_name='Fecha y hora de salida')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_guard.visitorvehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
