# Generated by Django 3.2.4 on 2021-08-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_guard', '0002_visitorparkinguse_visitorvehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorvehicle',
            name='dummy',
        ),
    ]
