/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 20-ene.-2021 10:39:57 a. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `apartamento` CASCADE
;

DROP TABLE IF EXISTS `configuraciones` CASCADE
;

DROP TABLE IF EXISTS `copropiedad` CASCADE
;

DROP TABLE IF EXISTS `menu` CASCADE
;

DROP TABLE IF EXISTS `pagos` CASCADE
;

DROP TABLE IF EXISTS `parqueadero` CASCADE
;

DROP TABLE IF EXISTS `registro_uso` CASCADE
;

DROP TABLE IF EXISTS `registro_visitantes` CASCADE
;

DROP TABLE IF EXISTS `turno` CASCADE
;

DROP TABLE IF EXISTS `usuario` CASCADE
;

DROP TABLE IF EXISTS `usuario_parqueadero` CASCADE
;

DROP TABLE IF EXISTS `vehiculo` CASCADE
;

/* Create Tables */

CREATE TABLE `apartamento`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_copropiedad` INT NOT NULL,
	`bloque` VARCHAR(50) NOT NULL,
	`apartamento` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Apartamento` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que guarda los apartamentos asociados a los usuarios'

;

CREATE TABLE `configuraciones`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_copropiedad` INT NOT NULL,
	`peso_maximo` DOUBLE(10,2) NOT NULL,
	`ejes_maximos` DOUBLE(10,2) NOT NULL,
	`dia_arqueo` VARCHAR(10) NOT NULL,
	`dia_alertas` VARCHAR(10) NOT NULL,
	`n_parqueaderos_carro` INT NOT NULL,
	`n_parqueaderos_moto` INT NOT NULL,
	`n_parqueaderos_carro_vis` INT NOT NULL,
	`n_parqueaderos_moto_vis` INT NOT NULL,
	`n_parqueaderos_bicicleta` INT NOT NULL,
	`n_parqueaderos_bicicleta_vis` INT NOT NULL,
	`tipo_pago_visitante` VARCHAR(10) NOT NULL COMMENT 'Hora, dia o minuto',
	`valor_pago_carro` DOUBLE(10,2) NOT NULL,
	`valor_pago_moto` DOUBLE(10,2) NOT NULL,
	`valor_pago_bicicleta` DOUBLE(10,2) NOT NULL,
	`tiempo_gracia` INT NOT NULL,
	`encabezado_recibo` VARCHAR(256) NOT NULL,
	`texto_responsabilidad` VARCHAR(256) NOT NULL,
	`pie_pagina_recibo` VARCHAR(256) NOT NULL,
	CONSTRAINT `PK_Configuraciones` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que guarda las configuraciones iniciales hechas por administración para la total configuracion de los parqueaderos.'

;

CREATE TABLE `copropiedad`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_administrador` INT NULL,
	`nombre` VARCHAR(50) NOT NULL,
	`direccion` VARCHAR(50) NOT NULL,
	`habilitada` TINYINT NOT NULL,
	CONSTRAINT `PK_Copropiedad` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que maneja las copropiedades en la aplicación'

;

CREATE TABLE `menu`
(
	`id_menu` INT NOT NULL AUTO_INCREMENT,
	`id_padre` INT NULL,
	`nombre` VARCHAR(50) NOT NULL,
	`tipo_usuario` CHAR(1) NOT NULL,
	`tiene_hijos` TINYINT NULL,
	`mostrar` TINYINT NULL,
	CONSTRAINT `PK_Menu` PRIMARY KEY (`id_menu` ASC)
)
COMMENT = 'Tabla para manejar el arbol de menus de acuerdo al tipo de usuario.'

;

CREATE TABLE `pagos`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_usuario` INT NOT NULL,
	`id_parqueadero` INT NOT NULL,
	`fecha_pago` DATE NOT NULL,
	`hora_pago` TIME NOT NULL,
	CONSTRAINT `PK_Pagos` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que registra las fechas de pago de los parqueaderos'

;

CREATE TABLE `parqueadero`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_copropiedad` INT NOT NULL,
	`id_usuario` INT NULL,
	`codigo` VARCHAR(50) NOT NULL,
	`area` DOUBLE(10,2) NOT NULL,
	`peso_admitido` DOUBLE(10,2) NOT NULL,
	`ejes_admitidos` INT NOT NULL,
	`codigo_barras` VARCHAR(50) NOT NULL,
	`admite_carro` BOOL NOT NULL,
	`admite_moto` BOOL NOT NULL,
	`admite_bicicleta` BOOL NOT NULL,
	`tipo` VARCHAR(10) NOT NULL,
	`en_uso` TINYINT NOT NULL DEFAULT 0,
	CONSTRAINT `PK_Parqueadero` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que guarda los datos de los parqueaderos existentes que hay en la copropiedad'

;

CREATE TABLE `registro_uso`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_vehiculo` INT NOT NULL,
	`fecha_ingreso` DATE NOT NULL,
	`fecha_salida` DATE NULL,
	`hora_ingreso` TIME NOT NULL,
	`hora_salida` TIME NULL,
	CONSTRAINT `PK_Registro_Uso` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que guarda el registro de uso de un parqueadero, es decir, la fecha y hora de entrada de un vehiculo y la fecha y hora de salida del mismo'

;

CREATE TABLE `registro_visitantes`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_parqueadero` INT NOT NULL,
	`nombre_responsable` VARCHAR(50) NOT NULL,
	`tipo_vehiculo` VARCHAR(50) NOT NULL,
	`marca` VARCHAR(50) NOT NULL,
	`color` VARCHAR(50) NOT NULL,
	`placa` VARCHAR(10) NOT NULL,
	`foto` VARCHAR(256) NOT NULL,
	`fecha_entrada` DATE NOT NULL,
	`hora_entrada` TIME NOT NULL,
	`fecha_salida` DATE NULL,
	`hora_salida` TIME NULL,
	CONSTRAINT `PK_registro_visitantes` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que guarda el registro de entrada y salida de los visitantes'

;

CREATE TABLE `turno`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_usuario` INT NOT NULL,
	`fecha_entrada` DATE NOT NULL,
	`fecha_salida` DATE NULL,
	`hora_entrada` TIME NOT NULL,
	`hora_salida` TIME NULL,
	`dinero_inicial` DOUBLE(10,2) NOT NULL,
	`dinero_final` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Turno` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla para registrar la información de los turnos de los guardias'

;

CREATE TABLE `usuario`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_copropiedad` INT NOT NULL,
	`id_apartamento` INT NULL,
	`usuario` VARCHAR(50) NULL,
	`password` VARCHAR(512) NULL,
	`tipo_usuario` CHAR(1) NOT NULL,
	`nombres` VARCHAR(50) NOT NULL,
	`apellidos` VARCHAR(50) NOT NULL,
	`tipo_identificacion` VARCHAR(3) NOT NULL,
	`identificacion` BIGINT NOT NULL,
	`telefono` INT NOT NULL,
	`celular` BIGINT NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`sancionado` BOOL NOT NULL DEFAULT False,
	`al_dia` BOOL NOT NULL DEFAULT True,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que guarda la información de los usuarios registrados en la aplicacion'

;

CREATE TABLE `usuario_parqueadero`
(
	`id_usuario_parqueadero` INT NOT NULL AUTO_INCREMENT,
	`id_usuario` INT NOT NULL,
	`id_parqueadero` INT NOT NULL,
	CONSTRAINT `PK_usuario_parqueadero` PRIMARY KEY (`id_usuario_parqueadero` ASC)
)
COMMENT = 'Tabla de rompimiento usuario-parqueadero'

;

CREATE TABLE `vehiculo`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`id_propietario` INT NOT NULL,
	`id_parqueadero` INT NULL,
	`marca` VARCHAR(50) NOT NULL,
	`modelo` VARCHAR(50) NOT NULL,
	`tipo` VARCHAR(50) NOT NULL,
	`color` VARCHAR(50) NOT NULL,
	`peso` DOUBLE(10,2) NOT NULL,
	`numero_ejes` VARCHAR(50) NOT NULL,
	`placa` VARCHAR(10) NOT NULL,
	`carta_propiedad` VARCHAR(256) NOT NULL,
	`soat` VARCHAR(256) NOT NULL,
	`foto` VARCHAR(256) NOT NULL,
	`fecha_vencimiento_soat` DATE NOT NULL,
	CONSTRAINT `PK_Vehiculo` PRIMARY KEY (`id` ASC)
)
COMMENT = 'Tabla que guarda la información de los vehiculos registrados por los usuarios'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `apartamento` 
 ADD INDEX `IXFK_Apartamento_Copropiedad` (`id_copropiedad` ASC)
;

ALTER TABLE `configuraciones` 
 ADD CONSTRAINT `UK_copropiedad` UNIQUE (`id_copropiedad` ASC)
;

ALTER TABLE `configuraciones` 
 ADD CONSTRAINT `CK_dia_arqueo` CHECK (dia_arqueo IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO'))
;

ALTER TABLE `configuraciones` 
 ADD CONSTRAINT `CK_dia_alertas` CHECK (dia_alertas IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO'))
;

ALTER TABLE `configuraciones` 
 ADD CONSTRAINT `CK_tipo_pago_visitante` CHECK (tipo_pago_visitante IN ('MINUTO','HORA','DIA'))
;

ALTER TABLE `configuraciones` 
 ADD INDEX `IXFK_Configuraciones_Copropiedad` (`id_copropiedad` ASC)
;

ALTER TABLE `copropiedad` 
 ADD CONSTRAINT `UK_nombre` UNIQUE (`nombre` ASC)
;

ALTER TABLE `copropiedad` 
 ADD CONSTRAINT `UK_administrador` UNIQUE (`id_administrador` ASC)
;

ALTER TABLE `copropiedad` 
 ADD INDEX `IXFK_Copropiedad_Usuario` (`id_administrador` ASC)
;

ALTER TABLE `menu` 
 ADD CONSTRAINT `CK_Tipo_usuario` CHECK (tipo_usuario IN ('A','C','G','R'))
;

ALTER TABLE `menu` 
 ADD INDEX `IXFK_Menu_Menu` (`id_padre` ASC)
;

ALTER TABLE `pagos` 
 ADD INDEX `IXFK_Pagos_Parqueadero` (`id_parqueadero` ASC)
;

ALTER TABLE `pagos` 
 ADD INDEX `IXFK_Pagos_Usuario` (`id_usuario` ASC)
;

ALTER TABLE `parqueadero` 
 ADD CONSTRAINT `UK_codigo` UNIQUE (`codigo` ASC)
;

ALTER TABLE `parqueadero` 
 ADD CONSTRAINT `UK_codigo_barras` UNIQUE (`codigo_barras` ASC)
;

ALTER TABLE `parqueadero` 
 ADD CONSTRAINT `CK_tipo` CHECK (tipo IN ('RESIDENTE','VISITANTE'))
;

ALTER TABLE `parqueadero` 
 ADD INDEX `IXFK_Parqueadero_Copropiedad` (`id_copropiedad` ASC)
;

ALTER TABLE `registro_uso` 
 ADD INDEX `IXFK_Registro_Uso_Vehiculo` (`id_vehiculo` ASC)
;

ALTER TABLE `registro_visitantes` 
 ADD CONSTRAINT `UK_placa` UNIQUE (`placa` ASC)
;

ALTER TABLE `registro_visitantes` 
 ADD CONSTRAINT `CK_tipo_vehiculo` CHECK (tipo_vehiculo in ('CARRO','MOTO','BICICLETA'))
;

ALTER TABLE `registro_visitantes` 
 ADD INDEX `IXFK_registro_visitantes_Parqueadero` (`id_parqueadero` ASC)
;

ALTER TABLE `turno` 
 ADD INDEX `IXFK_Turno_Usuario` (`id_usuario` ASC)
;

ALTER TABLE `usuario` 
 ADD CONSTRAINT `UK_usuario` UNIQUE (`usuario` ASC)
;

ALTER TABLE `usuario` 
 ADD CONSTRAINT `UK_identificacion` UNIQUE (`identificacion` ASC)
;

ALTER TABLE `usuario` 
 ADD CONSTRAINT `CK_tipo_identificacion` CHECK (tipo_identificacion IN ('CC','CE'))
;

ALTER TABLE `usuario` 
 ADD CONSTRAINT `CK_tipo_usuario` CHECK (tipo_usuario IN ('A','R','G'))
;

ALTER TABLE `usuario` 
 ADD INDEX `IXFK_Usuario_Copropiedad` (`id_copropiedad` ASC)
;

ALTER TABLE `usuario_parqueadero` 
 ADD INDEX `IXFK_usuario_parqueadero_Parqueadero` (`id_parqueadero` ASC)
;

ALTER TABLE `usuario_parqueadero` 
 ADD INDEX `IXFK_usuario_parqueadero_Usuario` (`id_usuario` ASC)
;

ALTER TABLE `vehiculo` 
 ADD CONSTRAINT `UK_placa` UNIQUE (`placa` ASC)
;

ALTER TABLE `vehiculo` 
 ADD CONSTRAINT `CK_tipo` CHECK (tipo in ('CARRO','MOTO','BICICLETA'))
;

ALTER TABLE `vehiculo` 
 ADD INDEX `IXFK_Vehiculo_Parqueadero` (`id_parqueadero` ASC)
;

ALTER TABLE `vehiculo` 
 ADD INDEX `IXFK_Vehiculo_Usuario` (`id_propietario` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `apartamento` 
 ADD CONSTRAINT `FK_Apartamento_Copropiedad`
	FOREIGN KEY (`id_copropiedad`) REFERENCES `copropiedad` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `configuraciones` 
 ADD CONSTRAINT `FK_Configuraciones_Copropiedad`
	FOREIGN KEY (`id_copropiedad`) REFERENCES `copropiedad` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `copropiedad` 
 ADD CONSTRAINT `FK_Copropiedad_Usuario`
	FOREIGN KEY (`id_administrador`) REFERENCES `usuario` (`id`) ON DELETE Set Null ON UPDATE Set Null
;

ALTER TABLE `menu` 
 ADD CONSTRAINT `FK_Menu_Menu`
	FOREIGN KEY (`id_padre`) REFERENCES `menu` (`id_menu`) ON DELETE Set Null ON UPDATE Set Null
;

ALTER TABLE `pagos` 
 ADD CONSTRAINT `FK_Pagos_Parqueadero`
	FOREIGN KEY (`id_parqueadero`) REFERENCES `parqueadero` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `pagos` 
 ADD CONSTRAINT `FK_Pagos_Usuario`
	FOREIGN KEY (`id_usuario`) REFERENCES `usuario` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `parqueadero` 
 ADD CONSTRAINT `FK_Parqueadero_Copropiedad`
	FOREIGN KEY (`id_copropiedad`) REFERENCES `copropiedad` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `registro_uso` 
 ADD CONSTRAINT `FK_Registro_Uso_Vehiculo`
	FOREIGN KEY (`id_vehiculo`) REFERENCES `vehiculo` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `registro_visitantes` 
 ADD CONSTRAINT `FK_registro_visitantes_Parqueadero`
	FOREIGN KEY (`id_parqueadero`) REFERENCES `parqueadero` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `turno` 
 ADD CONSTRAINT `FK_Turno_Usuario`
	FOREIGN KEY (`id_usuario`) REFERENCES `usuario` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `usuario` 
 ADD CONSTRAINT `FK_Usuario_Apartamento`
	FOREIGN KEY (`id_apartamento`) REFERENCES `apartamento` (`id`) ON DELETE Set Null ON UPDATE Set Null
;

ALTER TABLE `usuario` 
 ADD CONSTRAINT `FK_Usuario_Copropiedad`
	FOREIGN KEY (`id_copropiedad`) REFERENCES `copropiedad` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `usuario_parqueadero` 
 ADD CONSTRAINT `FK_usuario_parqueadero_Parqueadero`
	FOREIGN KEY (`id_parqueadero`) REFERENCES `parqueadero` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `usuario_parqueadero` 
 ADD CONSTRAINT `FK_usuario_parqueadero_Usuario`
	FOREIGN KEY (`id_usuario`) REFERENCES `usuario` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `vehiculo` 
 ADD CONSTRAINT `FK_Vehiculo_Parqueadero`
	FOREIGN KEY (`id_parqueadero`) REFERENCES `parqueadero` (`id`) ON DELETE Set Null ON UPDATE Set Null
;

ALTER TABLE `vehiculo` 
 ADD CONSTRAINT `FK_Vehiculo_Usuario`
	FOREIGN KEY (`id_propietario`) REFERENCES `usuario` (`id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
