# Generated by Django 3.2.4 on 2021-08-20 16:37

import admin_co_ownership.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=10, verbose_name='Número/Nombre del bloque')),
                ('apartment', models.CharField(max_length=10, verbose_name='Número/Nombre del apartamento')),
            ],
            options={
                'ordering': ['block', 'apartment'],
            },
        ),
        migrations.CreateModel(
            name='CoOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('enable', models.BooleanField(default=False, verbose_name='Habilitada')),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inhabitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('identification_type', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería')], default='CC', max_length=2, verbose_name='Tipo de identificación')),
                ('identification', models.BigIntegerField(unique=True, verbose_name='Documento de identificación')),
                ('cellphone', models.BigIntegerField(verbose_name='Número de celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('responsible', models.BooleanField(default=False, verbose_name='Es el responsable por el apartamento')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.apartment')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código de identificación')),
                ('area', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Área')),
                ('admitted_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso máximo admitido')),
                ('admitted_axis', models.IntegerField(verbose_name='Ejes máximos admitidos')),
                ('barcode', models.CharField(max_length=20, verbose_name='Código de barras del carnet')),
                ('supports_car', models.BooleanField(default=False, verbose_name='Admite carros')),
                ('supports_motorcycle', models.BooleanField(default=False, verbose_name='Admite motocicletas')),
                ('supports_bicycle', models.BooleanField(default=False, verbose_name='Admite bicicletas')),
                ('user_type', models.CharField(choices=[('R', 'Residentes'), ('V', 'Visitantes')], default='H', max_length=1, verbose_name='Para ser usado por')),
                ('in_use', models.BooleanField(default=False, verbose_name='Parqueadero en uso')),
                ('co_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.coownership')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InhabitantVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Marca del vehiculo')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo del vehiculo')),
                ('type', models.CharField(choices=[('C', 'Carro'), ('M', 'Moto'), ('B', 'Bicicleta')], max_length=1, verbose_name='Tipo de vehiculo')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('axis', models.IntegerField(verbose_name='Número de ejes')),
                ('plate', models.CharField(max_length=8, verbose_name='Número de placa')),
                ('picture', models.ImageField(upload_to=admin_co_ownership.models.photo_directory_path, verbose_name='Foto a color')),
                ('property_letter', models.FileField(upload_to=admin_co_ownership.models.property_letter_directory_path, verbose_name='Carta de propiedad')),
                ('soat', models.FileField(upload_to=admin_co_ownership.models.soat_directory_path, verbose_name='Soporte del SOAT')),
                ('due_date', models.DateField(verbose_name='Fecha de vencimiento del SOAT')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.inhabitant')),
                ('parking_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.parkingplace')),
            ],
            options={
                'ordering': ['brand', 'model', 'type'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso máximo permitido para vehículos')),
                ('max_axis', models.IntegerField(verbose_name='Ejes máximos permitidos para vehículos')),
                ('arching_day', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('C', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1, verbose_name='Día de la semana para arqueo de caja')),
                ('alerts_day', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('C', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1, verbose_name='Día de la semana para enviar alertas')),
                ('car_parking_num', models.IntegerField(default=0, verbose_name='Cantidad de parqueaderos para carros')),
                ('motorcycle_parking_num', models.IntegerField(default=0, verbose_name='Cantidad de parqueaderos para motocicletas')),
                ('bicycle_parking_num', models.IntegerField(default=0, verbose_name='Cantidad de parqueaderos para bicicletas')),
                ('visit_car_parking_num', models.IntegerField(default=0, verbose_name='Cantidad de parqueaderos de carros para visitantes')),
                ('visit_motorcycle_parking_num', models.IntegerField(default=0, verbose_name='Cantidad de parqueaderos de motocicletas para visitantes')),
                ('visit_bicycle_parking_num', models.IntegerField(default=0, verbose_name='Cantidad de parqueaderos de bicicletas para visitantes')),
                ('visit_payment_type', models.CharField(choices=[('H', 'Hora'), ('M', 'Minuto'), ('D', 'Día')], max_length=1, verbose_name='Tipo de pago para visitantes')),
                ('grace_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Tiempo de gracia para el periodo especificado')),
                ('car_payment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del pago para carros')),
                ('motorcycle_payment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del pago para motocicletas')),
                ('bicycle_payment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del pago para bicicletas')),
                ('receipt_header', models.TextField(verbose_name='Encabezado del recibo de pago')),
                ('receipt_footer', models.TextField(verbose_name='Pie de página del recibo de pago')),
                ('responsibility_text', models.TextField(verbose_name='Texto de responsabilidad')),
                ('co_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.coownership')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='co_ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.coownership'),
        ),
    ]
