# Generated by Django 3.2.4 on 2021-08-23 14:53

import admin_co_ownership.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitantvehicle',
            name='due_date',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento del SOAT'),
        ),
        migrations.AlterField(
            model_name='inhabitantvehicle',
            name='soat',
            field=models.FileField(null=True, upload_to=admin_co_ownership.models.soat_directory_path, verbose_name='Soporte del SOAT'),
        ),
    ]
