# Generated by Django 3.2.4 on 2021-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0002_auto_20210823_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitant',
            name='up_to_date',
            field=models.BooleanField(default=False, verbose_name='Al día con pago del parqueadero'),
        ),
    ]
