# Generated by Django 3.2.4 on 2021-08-23 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_co_ownership', '0003_inhabitant_up_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhabitantPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del pago')),
                ('inhabitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_co_ownership.inhabitant')),
            ],
        ),
    ]
